### ISSUE TITLE
How to run without GPU

### ISSUE THREAD

**Issue by TangentDeng** [WPZgithub/CEFCON#1]
Hi, glad to post first post! 
In 
```
CUDA = '0'
%%time
cefcon_results_dict = {}
for li, data_li in data.items():
    # We suggest setting up multiple repeats to minimize the randomness of the computation.
    cefcon_GRN_model = cf.NetModel(epochs=350, repeats=3, cuda=CUDA, seed=-1)
    cefcon_GRN_model.run(data_li)

    cefcon_results = cefcon_GRN_model.get_cefcon_results(edge_threshold_avgDegree=8)
    cefcon_results_dict[li] = cefcon_results
```
get error
```
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```
How to run without GPU?

**Comment by WPZgithub** [comment]
Hi, thanks for using CEFCON!

If you don't have a GPU device, you can set `CUDA='-1'`, which will utilize the CPUs to construct cell-lineage-specific GRNs. However, it's important to note that the computational time cost when using CPUs will be significantly higher.

**Comment by WPZgithub** [comment]
> Hi, glad to post first post! In
> 
> ```
> CUDA = '0'
> %%time
> cefcon_results_dict = {}
> for li, data_li in data.items():
>     # We suggest setting up multiple repeats to minimize the randomness of the computation.
>     cefcon_GRN_model = cf.NetModel(epochs=350, repeats=3, cuda=CUDA, seed=-1)
>     cefcon_GRN_model.run(data_li)
> 
>     cefcon_results = cefcon_GRN_model.get_cefcon_results(edge_threshold_avgDegree=8)
>     cefcon_results_dict[li] = cefcon_results
> ```
> 
> get error
> 
> ```
> RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
> ```
> 
> How to run without GPU?

Hi, thanks for using CEFCON!

If you don't have a GPU device, you can set CUDA='-1', which will utilize the CPUs to construct cell-lineage-specific GRNs. However, it's important to note that the computational time cost when using CPUs will be significantly higher.
